name: "Ensure develop branch is rebased with main"
on:
  push:
    branches:
      - "main"

jobs:
  rebase:
    name: Rebase develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Rebase develop
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          set -o xtrace

          GH_API_URI="https://api.github.com"
          GH_API_HEADER="Accept: application/vnd.github.v3+json"
          GH_API_AUTH_HEADER="Authorization: token ${GITHUB_TOKEN}"

          
          # USER_LOGIN=$(jq -r ".comment.user.login" "$GITHUB_EVENT_PATH")
          # user_resp=$(curl -X GET -s -H "${GH_API_AUTH_HEADER}" -H "${GH_API_HEADER}" \
          #   "${GH_API_URI}/users/${USER_LOGIN}")
          PUSHER_NAME=$(jq -r ".pusher.name" "$GITHUB_EVENT_PATH")
          PUSHER_EMAIL="$PUSHER_NAME@users.noreply.github.com"

          # Checkout or create a new develop branch
          git checkout develop || git checkout -b develop origin/main

          git config --global user.email "$PUSHER_EMAIL"
          git config --global user.name "$PUSHER_NAME (Rebase PR Action)"
          
          git rebase origin/main
          git push origin develop